services:
  database:
    image: postgres:15
    container_name: "postgresDb"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mongoDB:
    image: mongo:latest
    container_name: "LogsDB"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: "mongoExpress"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: LogsDB
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
          - mongoDB
  